### PR TITLE
Initial Frontend

### PR DESCRIPTION
**Pull request by emmaleengo**
## Related Issues and Dependencies

--

## This introduces a breaking change

- [ ] Yes
- [ X] No

## This Pull Request implements

Basic Homepage and Issues Page

## Description

Using the Carbon Library, I have created some rough drafts of both the homepage and issues page for Varangian.

### CODE REVIEW

**Review by saurabhpujar — COMMENTED** [review]
Shouldn't this flow into the gh-pages branch?

**Review by saurabhpujar — APPROVED** [review]
LGTM

**Review by KPostOffice — COMMENTED** [review]
So overall this looks alright to me, but I don't have a ton of experience with Javascript, let alone the React framework. From what you have shown in our calls, it looks good. I can either approve this or try to find someone better equipped than myself. WDYT?

**Comment by emmaleengo** [comment]
Added new changes, please review - modularized landing page and initial reading of CSV file

**Pull request closed without merging**
